FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build -- --configuration production

FROM nginx:1.27-alpine
COPY --from=build /app/dist/client/browser /usr/share/nginx/html/bingo
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
